server:
  port: 8700

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka,http://localhost:8802/eureka

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          # 这里填写本地仓库的地址  如果是远程仓库可直接写远程仓库的地址
          uri: file:///D:/Study/SpringCloudStudy/config-server/config
          # 这里填本地仓库或远程仓库的分支
          default-label: master