mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone: http://eureka01:8801/eureka, http://eureka01:8802/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
